### ISSUE TITLE
Can't build in xcode 10

### ISSUE THREAD

**Issue by buithuyen** [momodevelopment/MomoiOSSwiftSdk#2]
I'm facing a problem.
<img width="1484" alt="screen shot 2018-11-26 at 11 15 24 am" src="https://user-images.githubusercontent.com/5087522/48992861-bcbc0200-f16c-11e8-8d3a-d10643a34cbc.png">
Can you guys help me resolve it.
Thanks!

**Comment by momodevelopment** [comment]
I don't know exactly the problem you have, but I found some solution in there. Hope you will get one of them to fix this issue.

The first: Need to remove Info.plist from Pods > MomoiOSSwiftSdk > Support Files. Cmd+shift+k to clean your project and rebuild

If still be fail, try to do this.
Xcode, go to File->Project/Workspace settings -> Change the build system to Legacy Build system

Refer this thread may be help you.
https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce
